### PR TITLE
My enumerables

### PR DESCRIPTION
**Pull request by aliciapaz**
Create a file with versions for the array methods:
each
each_with_index
map
all?
any?
none?
count
inject

Add a version of map that accepts procs or blocks
Add a test for the my_inject method.

### CODE REVIEW

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've made laudable progress in this project.
However, some changes are required before it can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] It is not a good practice to merge a PR that has not been approved. 
- I observed that a TSE already reviewed this project, but I cannot see the previous reviewer's comments. This is a re-review. I'm supposed to check the last reviewer's comments and check if they've been fixed. 
- You should note that reviewing projects is a continuous process. By merging and closing the previous PR where the reviewer dropped their comment, you're breaking the chain of that process and it is not advisable. Please take note of this in subsequent projects and PRs.

- [x] All GitHub Action checks have failed. Kindly fix all rubocop errors before requesting another review.
- [x] You have a total of 8 errors reported from your project. 
- For #my_all?,  when a pattern other than Regex or a Class is given, it should return false if any of the collection does not match the pattern. At the moment, it returned true.
- For #my_any?, when a pattern other than Regex or a Class is given, it should return true if any of the collection matches the pattern. At the moment, it returned false.
- For #my_none?, when a pattern other than Regex or a Class is given, it should return false only if one of the collection matches the pattern. At the moment, it returned true.
- Your #my_inject should raises a "LocalJumpError" when no block or argument is given, but at the moment, nothing was raised.
- For #my_inject, when a block is given without an initial value, it should combine all elements of enum by applying a binary operation, specified by a block::range. At the moment, it raised a `NoMethodError: undefined method `[]' for 5..50:Range`.
- For #my_inject, when a block is given with an initial value, it should combine all elements of enum by applying a binary operation, specified by a block. At the moment, it raised a `NoMethodError: undefined method `[]' for 5..50:Range`.
- For #my_inject, when a symbol is specified without an initial value, it should combine each element of the collection by applying the symbol as a named method:range. At the moment, it raised a `NoMethodError: undefined method `[]' for 5..50:Range`.


* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @aliciapaz  & @jpdf00**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 
**Please check that:**
- [x] my_all? returns true if the block never returns false or nil.
- [x] my_all? when no block or argument is given returns true when none of the collection members are false or nil.
- [x] my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Integer.
- [x] my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric.
- [x] my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex.
- [x] my_any? when no block or argument is given returns false if at least one of the collection is not true.
- [x] my_none? when no block or argument is given returns true only if none of the collection members is true.


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by aliciapaz** [comment]
According to the documentation: 
[any?](https://ruby-doc.org/core-3.0.0/Array.html#method-i-any-3F)
With no block given and no argument, returns _true_ if _self_ has any truthy element.

**Review by MahmoudBakr23 — APPROVED** [review]
**### Status: Approve ✔👍**
Well done  @jpdf00 and  @aliciapaz
Great job implementing the changes requested by the previous TSEs.
Now you can merge and submit the project

**Pull request merged**
